[build]
  # No build command needed for static HTML
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for better SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# Form handling
[[forms]]
  name = "quote-request"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Custom 404 page (optional)
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404

# Environment-specific settings
[context.production.environment]
  HUGO_VERSION = "0.58.2"
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.58.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.58.2"